#!/usr/bin/with-contenv bash
# shellcheck shell=bash

umask "${UMASK}"

echo "
----------------------------------------------------------------------
ENVIRONMENT
----------------------------------------------------------------------
PUID            | ${PUID}
PGID            | ${PGID}
PUID_POSTGRES   | ${PUID_POSTGRES}
PGID_POSTGRES   | ${PGID_POSTGRES}
UMASK           | ${UMASK}
VERSION         | ${VERSION}
TZ              | ${TZ}
----------------------------------------------------------------------
"
