#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# Set the UID/PID for unifi-protect user, fix shell.
usermod -o -u "${PUID}" unifi-protect
usermod --shell /bin/bash unifi-protect
groupmod -o -g "${PGID}" unifi-protect

# Set the UID/PID for postgres user
usermod -o -u "${PUID_POSTGRES}" postgres
groupmod -o -g "${PGID_POSTGRES}" postgres
